import os
import uuid
from groq import Groq
from pathlib import Path

# Initialize Groq client
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Ensure autogenerated directory exists
OUTPUT_DIR = Path("static/audio")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def text_to_speech(text: str, voice: str = "troy") -> str:
    """
    Convert text to speech using Groq's API.
    
    Args:
        text (str): The text to convert to speech.
        voice (str): The voice ID to use (e.g., "troy", "hannah", "austin").
        
    Returns:
        str: The path to the generated audio file.
    """
    try:
        model = "canopylabs/orpheus-v1-english"
        
        response = client.audio.speech.create(
            model=model,
            voice=voice,
            input=text,
            response_format="wav"
        )
        
        # Generate a unique filename
        filename = f"speech_{uuid.uuid4().hex}.wav"
        file_path = OUTPUT_DIR / filename
        
        # Write binary content to file
        response.write_to_file(file_path)
            
        return str(file_path)

    except Exception as e:
        print(f"[TTS Error] {e}")
        raise e
